name: Wiki Update
description: Sync your wiki to files in your repository
branding:
  icon: book
  color: blue
inputs:
  repository:
    description: The repository housing the wiki
    required: true
    default: github.com/${{ github.repository }}
  token:
    description: The token to use when cloning and pushing wiki changes
    required: true
    default: ${{ github.token }}
  wiki-directory:
    description: The directory to use for your wiki contents
    required: true
    default: .github/wiki
  commit-message:
    description: The message to use when committing to the wiki
    required: true
    default: Update wiki ${{ github.sha }}
runs:
  using: composite
  steps:
    - id: index
      run: '"${GITHUB_ACTION_PATH%/}/src/index.sh"'
      shell: bash
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_WIKI_DIRECTORY: ${{ inputs.wiki-directory }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
