name: Wiki Update
description: 📖 Deploy docs from your source tree to the GitHub wiki
branding:
  icon: book
  color: blue
inputs:
  repository:
    description: >-
      The repository housing the wiki. Use this if you're publishing to a wiki
      that's not the current repository. You can include a domain prefix if you
      have a hosted GitHub instance that you want to push to. Default is
      github.repository with the implicit github.com domain.
    required: true
    default: github.com/${{ github.repository }}
  token:
    description: >-
      github.token is the default. This token is used when cloning and pushing
      wiki changes.
    required: true
    default: ${{ github.token }}
  path:
    description: >-
      The directory to use for your wiki contents. Default .github/wiki.
    required: true
    default: .github/wiki
  commit-message:
    description: >-
      The message to use when committing new content. Default is Update wiki
      github.sha. You probably don't need to change this, since this only
      applies if you look really closely in your wiki.
    required: true
    default: Update wiki ${{ github.sha }}
  dry-run:
    description: >-
      Whether or not to actually attempt to push changes back to the wiki
      itself. If this is set to true, we instead print the remote URL and do not
      push to the remote wiki. The default is false. This is useful for testing.
    required: true
    default: false
runs:
  using: node16
  main: "dist/index.js"
