name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: spenserblack/actions-tag-to-release@v1
        with:
          prerelease: auto
          draft: true
